import { test, expect } from '@playwright/test'

const button = (page, name) => page.getByRole('button', { name, exact: true })
const cell = (page, row, col) => page.getByRole('button', { name: new RegExp(`^Row ${row}, column ${col}:`) })
const statistic = (page, name) => page.locator('.stats-panel dl > div').filter({ has: page.getByText(name, { exact: true }) }).locator('dd')
const pageErrors = new WeakMap()

test.beforeEach(async ({ page }) => {
  const errors = []
  pageErrors.set(page, errors)
  page.on('pageerror', (error) => errors.push(error.message))
  page.on('console', (message) => { if (message.type() === 'error') errors.push(message.text()) })
  await page.goto('/')
})

test.afterEach(async ({ page }) => {
  expect(pageErrors.get(page)).toEqual([])
})

test('edit, pause, step, resume, clear and rerun', async ({ page }) => {
  await cell(page, 1, 1).click()
  await expect(cell(page, 1, 1)).toHaveClass(/cell-wall/)
  await page.getByLabel('Select animation speed').selectOption('slow')
  await button(page, 'Run').click()
  await button(page, 'Pause').click()
  await expect(page.getByRole('status')).toHaveText('Paused')
  await expect(cell(page, 1, 1)).toBeDisabled()
  await expect(button(page, 'Generate')).toBeDisabled()
  const before = Number(await statistic(page, 'Visited').textContent())
  await button(page, 'Step').click()
  await expect(statistic(page, 'Visited')).toHaveText(String(before + 1))
  await page.getByLabel('Select animation speed').selectOption('fast')
  await button(page, 'Resume').click()
  await expect(page.getByRole('status')).toHaveText('Complete')
  await expect(statistic(page, 'Path length')).toHaveText('14')
  await button(page, 'Clear search').click()
  await expect(cell(page, 1, 1)).toHaveClass(/cell-wall/)
  await expect(statistic(page, 'Visited')).toHaveText('0')
  await button(page, 'Run').click()
  await expect(page.getByRole('status')).toHaveText('Complete')
  await button(page, 'Reset board').click()
  await expect(page.locator('.grid .cell-wall')).toHaveCount(0)
})

test('all algorithms, weighted detour and no-route results', async ({ page }) => {
  await page.emulateMedia({ reducedMotion: 'reduce' })
  await page.getByLabel('Select drawing tool').selectOption('start')
  await cell(page, 1, 1).click()
  await page.getByLabel('Select drawing tool').selectOption('target')
  await cell(page, 1, 3).click()
  await page.getByLabel('Select drawing tool').selectOption('weight')
  await cell(page, 1, 2).click()
  for (const algorithm of ['bfs', 'dfs', 'dijkstra', 'astar', 'greedy']) {
    await page.getByLabel('Select algorithm').selectOption(algorithm)
    await expect(page.getByRole('status')).toHaveText('Ready')
    await button(page, 'Run').click()
    await expect(page.getByRole('status')).toHaveText('Complete')
    if (['dijkstra', 'astar'].includes(algorithm)) await expect(statistic(page, 'Cost')).toHaveText('4')
    else await expect(statistic(page, 'Cost')).toHaveText('6')
  }
  await page.getByLabel('Select drawing tool').selectOption('wall')
  await cell(page, 1, 2).click()
  await cell(page, 2, 1).click()
  for (const algorithm of ['bfs', 'dfs', 'dijkstra', 'astar', 'greedy']) {
    await page.getByLabel('Select algorithm').selectOption(algorithm)
    await button(page, 'Run').click()
    await expect(page.getByRole('status')).toHaveText('No path found')
    await expect(statistic(page, 'Cost')).toHaveText('—')
  }
})

test('maze selection is non-destructive; generation replaces terrain and preserves endpoints', async ({ page }) => {
  await expect(button(page, 'Generate')).toBeDisabled()
  await page.getByLabel('Select drawing tool').selectOption('weight')
  await cell(page, 1, 1).click()
  await page.getByLabel('Select maze pattern').selectOption('recursive-division')
  await expect(cell(page, 1, 1)).toHaveText('5')
  await expect(page.locator('.grid .cell-wall')).toHaveCount(0)
  await button(page, 'Generate').click()
  expect(await page.locator('.grid .cell-wall').count()).toBeGreaterThan(50)
  await expect(page.locator('.grid .cell-weight')).toHaveCount(0)
  await expect(cell(page, 8, 6)).toHaveText('S')
  await expect(cell(page, 8, 20)).toHaveText('T')
  await page.getByLabel('Select maze pattern').selectOption('random')
  await button(page, 'Generate').click()
  expect(await page.locator('.grid .cell-wall').count()).toBeGreaterThan(0)
  await expect(cell(page, 8, 6)).toHaveText('S')
  await expect(cell(page, 8, 20)).toHaveText('T')
})

test('dragging paints/removes once per cell and keyboard navigation stays in bounds', async ({ page }) => {
  await cell(page, 1, 1).hover()
  await page.mouse.down()
  await cell(page, 1, 2).hover()
  await cell(page, 1, 3).hover()
  await cell(page, 1, 2).hover()
  await cell(page, 1, 1).hover()
  await page.mouse.up()
  await expect(page.locator('.grid .cell-wall')).toHaveCount(3)
  await page.mouse.down()
  await cell(page, 1, 2).hover()
  await cell(page, 1, 3).hover()
  await page.mouse.up()
  await expect(page.locator('.grid .cell-wall')).toHaveCount(0)
  await cell(page, 1, 3).press('ArrowUp')
  await expect(cell(page, 1, 3)).toBeFocused()
  await cell(page, 1, 3).press('ArrowLeft')
  await expect(cell(page, 1, 2)).toBeFocused()
  await cell(page, 1, 2).press('Enter')
  await expect(cell(page, 1, 2)).toHaveClass(/cell-wall/)
  await cell(page, 1, 2).press('Space')
  await expect(cell(page, 1, 2)).not.toHaveClass(/cell-wall/)
  await expect(page.locator('.grid button[tabindex="0"]')).toHaveCount(1)
})

test('touch, narrow layouts and both themes', async ({ browser }) => {
  const context = await browser.newContext({ viewport: { width: 390, height: 844 }, hasTouch: true, isMobile: true, reducedMotion: 'reduce' })
  const page = await context.newPage()
  const errors = []
  page.on('pageerror', (error) => errors.push(error.message))
  await page.goto('/')
  await cell(page, 1, 1).tap()
  await expect(cell(page, 1, 1)).toHaveClass(/cell-wall/)
  for (const colorScheme of ['light', 'dark']) {
    await page.emulateMedia({ colorScheme, reducedMotion: 'reduce' })
    await button(page, 'Run').tap()
    await expect(page.getByRole('status')).toHaveText('Complete')
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
    await page.screenshot({ path: test.info().outputPath(`mobile-${colorScheme}.png`), fullPage: true })
    await button(page, 'Clear search').tap()
  }
  expect(errors).toEqual([])
  await context.close()
})
